### PR TITLE
Add composer package, re-organize

### PR DESCRIPTION
**Pull request by bendoh**
I want to be able to use this as a composer package, but not necessarily through wpackagist (as this hasn't been pushed into the WP plugin repository yet.)

I was hoping to use brunch as the build tool, but what I'm seeing is that brunch will silently exit when I try to run it, so I eventually gave up. I would definitely want to replace gulp with brunch, but if it doesn't work, it doesn't work! Hopefully someone else is able to figure out why. It's probably because of the rather unpredictable nature of node packages and I've probably installed a newer version of brunch that simply doesn't work.

Hopefully I'm wrong on that one.

### CODE REVIEW

**Comment by bendoh** [comment]
@marcaddeo please take a look at this and let me know if you have any suggestions on how I might approach this differently.

**Comment by marcaddeo** [comment]
Cool! I has comments :hamburger:
1. Since this is a Wordpress plugin, I don't think we want to autoload any of the files. We wouldn't be able to enable/disable it in the backend if it's always autoloaded.
2. We also need to require [`composer/installers`](https://github.com/composer/installers)
3. There should be a `"type": "wordpress-plugin"` configuration option set in the `composer.json`. This will tell Composer it's a Wordpress plugin and to install it into `wp-content/plugins/{$name}` instead of `vendor`. (oomphrock overrides this path)
4. Since it's a Wordpress plugin, and defined as `wordpress-plugin` in the `composer.json`, it's literally just being copied into the plugins directory. So, we also need to have the root of the directory be exactly as they should for a plugin.
   - We need to move the PHP stuff out of `src/` and back into the root
   - We need to distribute compiled assets. Someone installing this plugin shouldn't have to compile their own assets.
     - Not sure the best way to handle this in terms of version control, I wouldn't want to see compiled assets in every single commit... I wonder if we could have a script that creates a new tagged version, which would include the compiled assets.
5. It's a good practice to define a minimum php version for your package, e.g. add a  `require` for `"php": ">=5.4"`
6. There's no reason to supply a `minimum-stability`, since it currently has no requirements. I also wouldn't use `minimum-stability` without a reason, it can make weird things happen. And I'd always prefer `stable` packages unless there's a specific case. Furthermore, you can override `minimum-stability` on a per package basis with [`stability flags`](https://getcomposer.org/doc/04-schema.md#package-links) e.g. `"monolog/monolog": "5.0@dev"`
7. I'd add a real description so it can be used on packagist.org
8. The [`LICENSE`](https://github.com/oomphinc/WP-Forms-API/blob/master/LICENSE) file in our repo says GPL, not MIT. We need to update one of them.

**Comment by bendoh** [comment]
Awesome. Thanks for taking a look, I knew you'd know better than I knew but will now know because you knew and gave me your knew-ledge. Fanks!

Before I respond, let me just share with you a few goals I had with this setup:

This is not currently packaged as an official WordPress plugin and is thus inaccessible via the WordPress.org plugins repository, but I want it to eventually be hosted there, and thus become available on WPPackagist. However, I wouldn't want the "WordPress plugin" package to include any of the source files, e.g., SASS. I was planning on creating a build step that would build the WordPress plugin (as you mentioned in your responses) and update all the various version tags, etc, so that could make sure that I hit all the various pieces (maybe also performing the wp.org SVN repository workflow), and the final product kept on WordPress.org would be devoid of build files, and be just the core plugin components. I know we have examples of these scripts here at Oomph, and I'm sure that someone else has done this that we can draw from as well.

I also want to be able to include this repository as a full development environment for this plugin. This would be defined by the given `composer.json` file at the root of this repository, and would thus include all the build files / SASS files. In this case, I would just instruct composer to deploy these to some alternative install path, e.g., `/web/app/externals` so that the CSS files (and other artifacts) can be built, referenced and included from the web server and be automagically used as WordPress plugins a-la mu-plugins. I would tweak the bedrock-autoloader in the Oomphrock base platform to load plugins in this path from a `src` sub-directory to support this. (I would also rename the bedrock-autoloader to oomphrock-autoloader, bringing me to a small tangent: how do we deal with downstream changes if we renamed a file in oomphrock's `web/app/mu-plugins`?)

I would also like use this setup for WP-RTG and other "big lift" plugins we may develop in the future. Please let me know if I'm crazy, but it seems like a good idea :)

Repuestos:

1) Yes, if I go with the above approach I would definitely leave out the autoload entirely from the composer.json, and just have the (hacked) bedrock autoloader load the plugin from `src` one level deeper, i.e., `web/app/externals/wp-forms-api/src`.

2, 3, 4) I would put all this in the packaged plugin's composer.json file, which is distinct from the root `composer.json` file found in this repository.

5) Yes!

6) I think I'll have to study this one further, as I'm not exactly sure what the semantics of `minimum-stability` are; I think i might be mis-understanding what it applies to.

7) Yes, this would be part of the built plugin, would probably just appear right in `src/`.

8) Good catch. I will go with MIT; it's the easiest, however if you have a strong opinion about the chosen license, please do share.

**Comment by marcaddeo** [comment]
> However, I wouldn't want the "WordPress plugin" package to include any of the source files, e.g., SASS.

Why not? It's pretty typical for a Wordpress plugin to include their source files, and it's an open source product. No reason not to include these files so a person can hack away at it if they so please.

> I also want to be able to include this repository as a full development environment for this plugin. This would be defined by the given composer.json file at the root of this repository, and would thus include all the build files / SASS files. In this case, I would just instruct composer to deploy these to some alternative install path, e.g., /web/app/externals so that the CSS files (and other artifacts) can be built, referenced and included from the web server and be automagically used as WordPress plugins a-la mu-plugins. I would tweak the bedrock-autoloader in the Oomphrock base platform to load plugins in this path from a src sub-directory to support this. (I would also rename the bedrock-autoloader to oomphrock-autoloader, bringing me to a small tangent: how do we deal with downstream changes if we renamed a file in oomphrock's web/app/mu-plugins?)

I think this is overcomplicating something that is as simple as `cd web/app/plugins && git clone git@github.com/oomphinc/wp-forms-api.git` and then just working in that directory. What benefits would your proposed idea have?

---

So if the plan is to package this as a wordpress.org plugin, which I would recommend we do, I don't think we should split the repo into two (build files, and a dist version).

I think the best course of action is to just turn this repo into a legit wordpress.org plugin, keeping build files, committing compiled assets (git -f assets/) when releasing, and having a release script to push up to wordpress.org's SVN server.

If we do that, it negates us even needing to make a `composer.json` file for this repository as the wpackagist.org site doesn't require one to work. It just polls the wordpress.org svn server and updates their internal index every x hours. But, we could still add a `composer.json` incase someone wanted to do `composer require oomphinc/wp-forms-api` instead of `composer require wpackagist-plugin/wp-forms-api`. Why you'd do that... I don't know?

Regarding the LICENSE, I typically use MIT license as it's a bit more open. But I have no problem using either.

**Comment by bendoh** [comment]
> Why not? It's pretty typical for a Wordpress plugin to include their source files, and it's an open source product. No reason not to include these files so a person can hack away at it if they so please.

If they wanted to contribute to the project, I'd prefer they did that through GitHub anyway. I'd like to keep any WordPress plugins that we produce free of cruft and fully packaged for distribution. Also with some level of branding.

> I think this is overcomplicating something that is as simple as cd web/app/plugins && git clone git@github.com/oomphinc/wp-forms-api.git and then just working in that directory. What benefits would your proposed idea have?

I don't think this is any more or less complicated than that. It could be even simpler, as within an Oomphrock project we could just do `composer require oomphinc/wp-forms-api` and be done with it. We can prefer using the source if we wanted to work on the plugin in those situations. OR we could just (eventually) go with the packaged distribution of the plugin from wpackagist, when this thing finally lands in the wp.org repository.

I like this concept: It's clean and allows us to maintain the distributed WordPress plugin separate from the source files and metadata. We can keep build files and test code (if we were writing it) outside of the WordPress.org repository, and simply link to the github repo for contribution purposes. This would also allow us to create plugins down the line that aren't exactly open source: we could obfuscate, minify, and compact the generated code as necessary if we wanted to productize a plugin.

I've already made the necessary modifications to the bedrock-autoloader to support this (within BC) and it works beautifully: The plugins show up correctly within the back-end and the asset paths are re-written as necessary.

My overall feeling here is that this structure is similar to a base development platform just for developing WordPress plugins. We can make them more-or-less open as we want by changing how the build artifacts are generated and included in the distribution package that's sent to WordPress.org.

**Comment by bendoh** [comment]
OK, been noodling this all day, and I'm going to concede that you're right! All of my experiments are showing me that it's just added overhead to plop all this down one directory further, and I should be able to use these more easily. Gonna close this out and re-open it with a different concept when I get back from my trip.

**Pull request closed without merging**
